# @package _group_
train:
  Resize:
    size: [256, 256]
  ColorJitter:
    saturation: 0.5
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

test:
  Resize:
    size: [256, 256]
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
